"""FPE8: distill a dense temporal hazard teacher into exact-K sparse readouts.

The dense teacher sees the full FPE7 observable and residual-state blocks. A
student reads only K coordinates of the current L18 residual delta plus ten
confidence scalars. Teacher targets for student-training rows are generated by
inner grouped out-of-fold models, while all reported predictions come from an
untouched outer fold.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import matplotlib.pyplot as plt
import numpy as np
import torch
import yaml
from transformers import AutoTokenizer

from scripts.poc_fpe3_trajectory_dynamics import fit_scalers, score_metrics, transform
from scripts.poc_fpe5_first_divergence_hazard import load_event_table
from scripts.poc_fpe6_single_trajectory_filter import (
    fit_logistic,
    logistic_predict,
    solve_ridge,
)
from scripts.poc_fpe7_observability_utility import (
    EPS,
    binary_metrics,
    event_onsets,
    fit_method_model,
    group_fold_ids,
    predict_method_model,
)


DEFAULT_K = (8, 16, 32, 64, 128, 256)
METHODS = ("dynamic_direct", "dynamic_distill", "shared_distill", "random_direct")
TARGET_FPRS = (0.05, 0.10, 0.20)


def parse_k_values(value: str) -> tuple[int, ...]:
    output = tuple(sorted({int(item) for item in value.split(",") if item.strip()}))
    if not output or min(output) <= 0:
        raise ValueError("K values must be positive")
    return output


def stage_arrays(states: dict[str, np.ndarray], stage: int) -> tuple[np.ndarray, np.ndarray]:
    raw = (
        states[f"raw_T{stage}_L18"].astype(np.float32)
        - states["raw_T0_L18"].astype(np.float32)
    )
    confidence = np.concatenate((
        states["confidence_T0"].astype(np.float32),
        states[f"confidence_T{stage}"].astype(np.float32),
    ), axis=1)
    return raw, confidence


def inner_teacher_targets(
    states: dict[str, np.ndarray],
    stage: int,
    labels: np.ndarray,
    valid: np.ndarray,
    outer_train: np.ndarray,
    fold_ids: np.ndarray,
    device: str,
) -> np.ndarray:
    output = np.full(len(labels), np.nan, dtype=np.float64)
    inner_folds = sorted(np.unique(fold_ids[outer_train]).tolist())
    for inner_fold in inner_folds:
        inner_test = outer_train & (fold_ids == inner_fold) & valid
        inner_train = outer_train & (fold_ids != inner_fold) & valid
        if not inner_test.any():
            continue
        model = fit_method_model(
            states, stage, "dense", labels, inner_train, device, pair_state=False
        )
        output[inner_test] = predict_method_model(
            model, states, stage, "dense"
        )[inner_test]
    if not np.isfinite(output[outer_train & valid]).all():
        raise RuntimeError(f"Missing inner teacher targets at T{stage}")
    return output


def fit_importance(
    raw: np.ndarray,
    confidence: np.ndarray,
    target: np.ndarray,
    train: np.ndarray,
    device: str,
) -> tuple[np.ndarray, dict]:
    confidence_scaler = fit_scalers([confidence], train)
    confidence_features = transform([confidence], confidence_scaler)
    baseline = fit_logistic(confidence_features[train], target[train], ridge=0.05)
    baseline_probability = logistic_predict(baseline, confidence_features)
    residual_target = target - baseline_probability

    raw_scaler = fit_scalers([raw], train)
    raw_features = transform([raw], raw_scaler)
    _, weights = solve_ridge(raw_features[train], residual_target[train], device)
    importance = np.abs(weights).astype(np.float64)
    diagnostics = {
        "importance_l1": float(importance.sum()),
        "importance_max": float(importance.max()),
        "target_mean": float(np.mean(target[train])),
    }
    return importance, diagnostics


def fit_sparse_student(
    raw: np.ndarray,
    confidence: np.ndarray,
    target: np.ndarray,
    hard_labels: np.ndarray,
    train: np.ndarray,
    support: np.ndarray,
) -> dict:
    blocks = [raw[:, support], confidence]
    scalers = fit_scalers(blocks, train)
    features = transform(blocks, scalers)
    soft_model = fit_logistic(features[train], target[train], ridge=0.02)
    soft_probability = logistic_predict(soft_model, features)
    # A one-dimensional calibration preserves the sparse support and converts
    # teacher matching into a pointwise hard-event probability.
    calibrator = fit_logistic(
        np.log(
            np.clip(soft_probability[train], EPS, 1 - EPS)
            / np.clip(1 - soft_probability[train], EPS, 1 - EPS)
        )[:, None],
        hard_labels[train],
        ridge=0.05,
    )
    return {
        "support": support.astype(np.int32),
        "scalers": scalers,
        "soft_model": soft_model,
        "calibrator": calibrator,
    }


def predict_sparse_student(
    model: dict, raw: np.ndarray, confidence: np.ndarray
) -> np.ndarray:
    blocks = [raw[:, model["support"]], confidence]
    features = transform(blocks, model["scalers"])
    soft_probability = logistic_predict(model["soft_model"], features)
    soft_logit = np.log(
        np.clip(soft_probability, EPS, 1 - EPS)
        / np.clip(1 - soft_probability, EPS, 1 - EPS)
    )
    return logistic_predict(model["calibrator"], soft_logit[:, None])


def top_k(importance: np.ndarray, k: int) -> np.ndarray:
    k = min(k, len(importance))
    return np.sort(np.argpartition(-importance, k - 1)[:k]).astype(np.int32)


def normalized_importance(importance: np.ndarray) -> np.ndarray:
    total = float(importance.sum())
    return importance / total if total > 0 else np.zeros_like(importance)


def kl_bernoulli(target: np.ndarray, prediction: np.ndarray) -> float:
    target = np.clip(target, EPS, 1 - EPS)
    prediction = np.clip(prediction, EPS, 1 - EPS)
    return float(np.mean(
        target * np.log(target / prediction)
        + (1 - target) * np.log((1 - target) / (1 - prediction))
    ))


def jaccard(left: np.ndarray, right: np.ndarray) -> float:
    left_set = set(map(int, left))
    right_set = set(map(int, right))
    return float(len(left_set & right_set) / max(len(left_set | right_set), 1))


def trajectory_max(
    predictions: dict[tuple[str, int | None, int], np.ndarray],
    table: dict[str, np.ndarray],
    rows: np.ndarray,
    method: str,
    k: int | None,
    stages: tuple[int, ...],
) -> np.ndarray:
    output = np.full(table["risk"].shape[1], -np.inf, dtype=np.float64)
    for stage in stages:
        score = predictions[(method, k, stage)]
        selected = rows & table["risk"][stage] & np.isfinite(score)
        output[selected] = np.maximum(output[selected], score[selected])
    return output


def utility_summary(
    predictions: dict[tuple[str, int | None, int], np.ndarray],
    table: dict[str, np.ndarray],
    final_labels: np.ndarray,
    onsets: np.ndarray,
    fold_ids: np.ndarray,
    methods: list[tuple[str, int | None]],
    stages: tuple[int, ...],
) -> list[dict]:
    records = []
    for fold in range(5):
        test = fold_ids == fold
        calibration = fold_ids == ((fold + 1) % 5)
        for method, k in methods:
            calibration_correct = calibration & (final_labels == 0)
            maxima = trajectory_max(
                predictions, table, calibration_correct, method, k, stages
            )
            maxima = maxima[np.isfinite(maxima)]
            for target_fpr in TARGET_FPRS:
                threshold = float(np.quantile(
                    maxima, 1 - target_fpr, method="higher"
                )) if len(maxima) else 1.0
                alert_stage = np.full(len(final_labels), -1, dtype=np.int8)
                for stage in stages:
                    score = predictions[(method, k, stage)]
                    selected = (
                        test & table["risk"][stage] & (alert_stage < 0)
                        & np.isfinite(score) & (score >= threshold)
                    )
                    alert_stage[selected] = stage
                correct = test & (final_labels == 0)
                # A monitor whose first read is T1 cannot warn before a T0 event.
                eligible_error = test & (final_labels == 1) & (onsets >= stages[0])
                false_alert = correct & (alert_stage >= 0)
                detected = (
                    eligible_error & (alert_stage >= 0) & (alert_stage <= onsets)
                )
                lead = onsets[detected] - alert_stage[detected] + 1
                records.append({
                    "fold": fold,
                    "method": method,
                    "k": k,
                    "target_fpr": target_fpr,
                    "n_correct": int(correct.sum()),
                    "n_eligible_error": int(eligible_error.sum()),
                    "false_alert": int(false_alert.sum()),
                    "detected": int(detected.sum()),
                    "lead_sum": float(lead.sum()),
                })
    output = []
    for method, k in methods:
        for target_fpr in TARGET_FPRS:
            selected = [
                row for row in records
                if row["method"] == method and row["k"] == k
                and row["target_fpr"] == target_fpr
            ]
            totals = {
                key: sum(row[key] for row in selected)
                for key in ("n_correct", "n_eligible_error", "false_alert", "detected")
            }
            lead_sum = sum(row["lead_sum"] for row in selected)
            output.append({
                "method": method,
                "k": k,
                "target_fpr": target_fpr,
                **totals,
                "actual_fpr": float(totals["false_alert"] / max(totals["n_correct"], 1)),
                "pre_event_recall": float(totals["detected"] / max(totals["n_eligible_error"], 1)),
                "mean_token_lead": float(lead_sum / max(totals["detected"], 1)),
            })
    return output


def make_figures(payload: dict, prefix: str) -> list[str]:
    figure_dir = ROOT / "paper" / "figures"
    figure_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    k_values = payload["k_values"]

    fig, axes = plt.subplots(1, len(payload["stages"]), figsize=(12.5, 3.8), sharey=True)
    for axis, stage in zip(axes, payload["stages"]):
        teacher = next(
            row for row in payload["stage_summary"]
            if row["stage"] == f"T{stage}" and row["method"] == "teacher"
        )["within_question_auroc_macro"]
        axis.axhline(teacher, color="#222222", linestyle="--", label="teacher")
        for method, color in (
            ("dynamic_direct", "#D55E00"),
            ("dynamic_distill", "#009E73"),
            ("shared_distill", "#0072B2"),
            ("random_direct", "#999999"),
        ):
            selected = [
                row for row in payload["stage_summary"]
                if row["stage"] == f"T{stage}" and row["method"] == method
            ]
            selected.sort(key=lambda row: row["k"])
            axis.plot(
                [row["k"] for row in selected],
                [row["within_question_auroc_macro"] for row in selected],
                marker="o", color=color, label=method,
            )
        axis.set_xscale("log", base=2)
        axis.set_xticks(k_values, [str(k) for k in k_values], rotation=45)
        axis.set_title(f"T{stage} -> T{stage + 1}")
        axis.set_xlabel("Residual coordinates K")
        axis.grid(alpha=0.2)
    axes[0].set_ylabel("Within-question AUROC")
    axes[-1].legend(frameon=False, fontsize=8)
    fig.tight_layout()
    path = figure_dir / f"{prefix}_capacity_curve.png"
    fig.savefig(path, dpi=220)
    plt.close(fig)
    paths.append(str(path))

    fig, ax = plt.subplots(figsize=(6.5, 4.2))
    utility = [
        row for row in payload["utility"]
        if row["target_fpr"] == 0.10 and row["method"] in (
            "dynamic_direct", "dynamic_distill", "shared_distill"
        )
    ]
    for method, color in (
        ("dynamic_direct", "#D55E00"),
        ("dynamic_distill", "#009E73"),
        ("shared_distill", "#0072B2"),
    ):
        selected = sorted(
            [row for row in utility if row["method"] == method],
            key=lambda row: row["k"],
        )
        ax.plot(
            [row["actual_fpr"] for row in selected],
            [row["pre_event_recall"] for row in selected],
            marker="o", label=method, color=color,
        )
        for row in selected:
            ax.annotate(str(row["k"]), (row["actual_fpr"], row["pre_event_recall"]), fontsize=7)
    teacher = next(
        row for row in payload["utility"]
        if row["target_fpr"] == 0.10 and row["method"] == "teacher"
    )
    ax.scatter(
        [teacher["actual_fpr"]], [teacher["pre_event_recall"]],
        marker="*", s=140, color="#222222", label="teacher",
    )
    ax.set_xlabel("Held-out trajectory FPR")
    ax.set_ylabel("Strict pre-event recall")
    ax.set_xlim(left=0)
    ax.set_ylim(0, 1)
    ax.grid(alpha=0.2)
    ax.legend(frameon=False)
    fig.tight_layout()
    path = figure_dir / f"{prefix}_utility_curve.png"
    fig.savefig(path, dpi=220)
    plt.close(fig)
    paths.append(str(path))
    return paths


def render_markdown(payload: dict, path: Path) -> None:
    lines = [
        "# FPE8 Sparse Risk Distillation Results", "",
        f"Dataset: `{payload['data_path']}`  ",
        f"Distillation hard-label weight: {payload['hard_label_weight']:.2f}  ",
        f"K values: {payload['k_values']}", "",
        "## Capacity Curve", "",
        "| Stage | Method | K | Within-question AUROC | Teacher retention | KL to teacher |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for row in payload["stage_summary"]:
        if row["method"] in ("teacher", "observed") or row.get("k") in (16, 64, 256):
            retention = row.get("teacher_information_retention")
            kl = row.get("kl_to_teacher")
            lines.append(
                f"| {row['stage']} | {row['method']} | {row.get('k') or '-'} | "
                f"{row['within_question_auroc_macro']:.3f} | "
                f"{'-' if retention is None else f'{retention:.3f}'} | "
                f"{'-' if kl is None else f'{kl:.4f}'} |"
            )
    lines.extend([
        "", "## Strict Pre-Event Utility at Nominal 10% FPR", "",
        "| Method | K | Actual FPR | Recall | Token lead |",
        "|---|---:|---:|---:|---:|",
    ])
    for row in payload["utility"]:
        if row["target_fpr"] == 0.10 and (
            row["method"] in ("teacher", "observed") or row.get("k") in (16, 64, 256)
        ):
            lines.append(
                f"| {row['method']} | {row.get('k') or '-'} | "
                f"{row['actual_fpr']:.3f} | {row['pre_event_recall']:.3f} | "
                f"{row['mean_token_lead']:.2f} |"
            )
    lines.extend(["", "## Support Dynamics", ""])
    lines.append("| K | Adjacent-stage Jaccard (dynamic distill) | Cross-fold Jaccard |")
    lines.append("|---:|---:|---:|")
    for row in payload["support_summary"]:
        lines.append(
            f"| {row['k']} | {row['adjacent_stage_jaccard_mean']:.3f} | "
            f"{row['cross_fold_jaccard_mean']:.3f} |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run(args: argparse.Namespace) -> dict:
    k_values = parse_k_values(args.k_values)
    stages = tuple(range(1, args.max_stage + 1))
    config = yaml.safe_load((ROOT / args.config).read_text(encoding="utf-8"))
    tokenizer = AutoTokenizer.from_pretrained(
        config["model"]["name"], local_files_only=True
    )
    data_path = ROOT / args.data
    cache_path = ROOT / args.cache
    _, states, event_data = load_event_table(tokenizer, data_path, cache_path)
    table = event_data["table"]
    fold_ids = group_fold_ids(states["pair_ids"].astype(str), args.seed)
    question_ids = states["question_ids"].astype(str)
    final_labels = states["labels"].astype(np.int8)
    onsets = event_onsets(table)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    n = len(final_labels)

    predictions: dict[tuple[str, int | None, int], np.ndarray] = {}
    for stage in stages:
        predictions[("teacher", None, stage)] = np.full(n, np.nan)
        predictions[("observed", None, stage)] = np.full(n, np.nan)
        for method in METHODS:
            for k in k_values:
                predictions[(method, k, stage)] = np.full(n, np.nan)

    support_store: dict[tuple[int, int, str, int], np.ndarray] = {}
    diagnostics = []
    for outer_fold in range(5):
        outer_test_group = fold_ids == outer_fold
        outer_train_group = ~outer_test_group
        stage_data = {}
        for stage in stages:
            valid = table["risk"][stage]
            labels = table["event"][stage].astype(np.int8)
            train = outer_train_group & valid
            test = outer_test_group & valid
            teacher_oof = inner_teacher_targets(
                states, stage, labels, valid, outer_train_group,
                fold_ids, device,
            )
            teacher_model = fit_method_model(
                states, stage, "dense", labels, train, device, pair_state=False
            )
            teacher_probability = predict_method_model(
                teacher_model, states, stage, "dense"
            )
            observed_model = fit_method_model(
                states, stage, "observed", labels, train, device
            )
            observed_probability = predict_method_model(
                observed_model, states, stage, "observed"
            )
            predictions[("teacher", None, stage)][test] = teacher_probability[test]
            predictions[("observed", None, stage)][test] = observed_probability[test]

            raw, confidence = stage_arrays(states, stage)
            direct_target = labels.astype(np.float64)
            distill_target = direct_target.copy()
            distill_target[train] = (
                args.hard_label_weight * direct_target[train]
                + (1 - args.hard_label_weight) * teacher_oof[train]
            )
            direct_importance, direct_diag = fit_importance(
                raw, confidence, direct_target, train, device
            )
            distill_importance, distill_diag = fit_importance(
                raw, confidence, distill_target, train, device
            )
            stage_data[stage] = {
                "valid": valid, "labels": labels, "train": train, "test": test,
                "raw": raw, "confidence": confidence,
                "direct_target": direct_target, "distill_target": distill_target,
                "direct_importance": direct_importance,
                "distill_importance": distill_importance,
            }
            diagnostics.append({
                "outer_fold": outer_fold, "stage": f"T{stage}",
                "n_train": int(train.sum()), "n_test": int(test.sum()),
                "teacher_oof_auroc": binary_metrics(
                    labels[train], teacher_oof[train]
                )["auroc"],
                "direct_importance": direct_diag,
                "distill_importance": distill_diag,
            })

        shared_importance = sum(
            normalized_importance(stage_data[stage]["distill_importance"])
            for stage in stages
        )
        rng = np.random.default_rng(args.seed * 100 + outer_fold)
        for k in k_values:
            shared_support = top_k(shared_importance, k)
            for stage in stages:
                data = stage_data[stage]
                supports = {
                    "dynamic_direct": top_k(data["direct_importance"], k),
                    "dynamic_distill": top_k(data["distill_importance"], k),
                    "shared_distill": shared_support,
                    "random_direct": np.sort(
                        rng.choice(data["raw"].shape[1], size=k, replace=False)
                    ).astype(np.int32),
                }
                targets = {
                    "dynamic_direct": data["direct_target"],
                    "dynamic_distill": data["distill_target"],
                    "shared_distill": data["distill_target"],
                    "random_direct": data["direct_target"],
                }
                for method in METHODS:
                    support = supports[method]
                    model = fit_sparse_student(
                        data["raw"], data["confidence"], targets[method],
                        data["labels"], data["train"], support,
                    )
                    probability = predict_sparse_student(
                        model, data["raw"], data["confidence"]
                    )
                    predictions[(method, k, stage)][data["test"]] = probability[data["test"]]
                    support_store[(outer_fold, stage, method, k)] = support

    stage_summary = []
    for stage in stages:
        valid = table["risk"][stage]
        labels = table["event"][stage].astype(np.int8)
        teacher_probability = predictions[("teacher", None, stage)]
        observed_probability = predictions[("observed", None, stage)]
        teacher_metrics = binary_metrics(labels[valid], teacher_probability[valid])
        observed_metrics = binary_metrics(labels[valid], observed_probability[valid])
        for method, k in [("teacher", None), ("observed", None)] + [
            (method, k) for method in METHODS for k in k_values
        ]:
            probability = predictions[(method, k, stage)]
            metrics = binary_metrics(labels[valid], probability[valid])
            within, _ = score_metrics(labels, probability, question_ids, valid)
            row = {
                "stage": f"T{stage}", "method": method, "k": k,
                **metrics,
                "within_question_auroc_macro": within["within_question_auroc_macro"],
                "n_rows": int(valid.sum()), "n_events": int(labels[valid].sum()),
            }
            if method not in ("teacher", "observed"):
                denominator = observed_metrics["nll_nats"] - teacher_metrics["nll_nats"]
                row["teacher_information_retention"] = (
                    float((observed_metrics["nll_nats"] - metrics["nll_nats"]) / denominator)
                    if abs(denominator) > 1e-8 else None
                )
                row["kl_to_teacher"] = kl_bernoulli(
                    teacher_probability[valid], probability[valid]
                )
                row["coordinate_fraction"] = float(k / states["raw_T0_L18"].shape[1])
            stage_summary.append(row)

    support_summary = []
    for k in k_values:
        adjacent = []
        cross_fold = []
        for fold in range(5):
            for left, right in zip(stages[:-1], stages[1:]):
                adjacent.append(jaccard(
                    support_store[(fold, left, "dynamic_distill", k)],
                    support_store[(fold, right, "dynamic_distill", k)],
                ))
        for stage in stages:
            for left in range(5):
                for right in range(left + 1, 5):
                    cross_fold.append(jaccard(
                        support_store[(left, stage, "dynamic_distill", k)],
                        support_store[(right, stage, "dynamic_distill", k)],
                    ))
        support_summary.append({
            "k": k,
            "adjacent_stage_jaccard_mean": float(np.mean(adjacent)),
            "cross_fold_jaccard_mean": float(np.mean(cross_fold)),
            "adjacent_stage_jaccard_values": adjacent,
            "cross_fold_jaccard_values": cross_fold,
        })

    utility_methods = [("teacher", None), ("observed", None)] + [
        (method, k) for method in METHODS for k in k_values
    ]
    utility = utility_summary(
        predictions, table, final_labels, onsets, fold_ids,
        utility_methods, stages,
    )
    payload = {
        "experiment": "FPE8 dense temporal teacher to exact-K sparse dynamic readout",
        "model": config["model"]["name"],
        "data_path": str(data_path), "cache_path": str(cache_path),
        "seed": args.seed, "device": device,
        "stages": list(stages), "k_values": list(k_values),
        "hard_label_weight": args.hard_label_weight,
        "protocol": {
            "outer_test": "five pair_id-grouped folds",
            "teacher_target": "inner grouped OOF dense-teacher probabilities",
            "student_input": "K L18 residual-delta coordinates plus T0/current confidence",
            "dynamic_support": "stage-specific exact-K support",
            "shared_support": "one exact-K support shared across evaluated stages",
            "utility": "strictly pre-event, T1 monitor start, separate OOF calibration fold",
        },
        "label_agreement": event_data["agreement"],
        "dense_teacher_input_dimensions": 5642,
        "student_input_dimensions": {str(k): k + 10 for k in k_values},
        "stage_summary": stage_summary,
        "support_summary": support_summary,
        "utility": utility,
        "fit_diagnostics": diagnostics,
    }
    output_path = ROOT / args.output
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    payload["figures"] = make_figures(payload, args.prefix)
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    markdown_path = ROOT / "paper" / f"{args.prefix.upper()}_SPARSE_DISTILLATION_RESULTS.md"
    render_markdown(payload, markdown_path)
    print(f"saved -> {output_path}")
    print(f"saved -> {markdown_path}")
    for stage in stages:
        teacher = next(
            row for row in stage_summary
            if row["stage"] == f"T{stage}" and row["method"] == "teacher"
        )
        print(f"T{stage} teacher within={teacher['within_question_auroc_macro']:.4f}")
        for k in (min(k_values), 64 if 64 in k_values else k_values[len(k_values)//2], max(k_values)):
            row = next(
                row for row in stage_summary
                if row["stage"] == f"T{stage}"
                and row["method"] == "dynamic_distill" and row["k"] == k
            )
            print(
                f"  distill K={k:<3} within={row['within_question_auroc_macro']:.4f} "
                f"retention={row['teacher_information_retention']:.3f}"
            )
    for row in utility:
        if row["target_fpr"] == 0.10 and (
            row["method"] == "teacher"
            or (row["method"] == "dynamic_distill" and row["k"] in (64, 256))
        ):
            print(
                f"utility {row['method']} K={row['k']} "
                f"fpr={row['actual_fpr']:.3f} recall={row['pre_event_recall']:.3f}"
            )
    return payload


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default="data/v37_2wiki_trajectory.jsonl")
    parser.add_argument("--cache", default="outputs/cache/v37_2wiki_trajectory_states.npz")
    parser.add_argument("--config", default="configs/default.yaml")
    parser.add_argument("--output", default="outputs/poc_fpe8_sparse_risk_distillation_results.json")
    parser.add_argument("--prefix", default="fpe8")
    parser.add_argument("--max-stage", type=int, default=3)
    parser.add_argument("--k-values", default=",".join(map(str, DEFAULT_K)))
    parser.add_argument("--hard-label-weight", type=float, default=0.25)
    parser.add_argument("--seed", type=int, default=42)
    run(parser.parse_args())
